### ISSUE TITLE
Identation lost after collapsing

### ISSUE THREAD

**Issue by nmase88** [Keflon/FunctionZero.Maui.Controls#1]
The Indentation of child nodes is lost after you collapse and then reexpand the parent.

**Comment by Keflon** [comment]
Thanks @nmase88 - it looks like a few things are broken after I updated to VS 17.4.0 Preview 1.0. 
Problems look to be related to recycling CollectionView items, I'll take a look after the weekend.

**Comment by Keflon** [comment]
@nmase88 I've fixed this and updated the NuGet package to version 1.0.2. Thanks for the report and please let me know if you find any more issues.

**Comment by nmase88** [comment]
Yeah I thought that was probably the case. Thank you :-)

**Comment by nmase88** [comment]
Thats great thanks very much 🙂 yeah will let you know
