### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by mortenn** [Keflon/FunctionZero.Maui.Controls#10]
Hello,
I was attempting to build a fairly simple Maui app using your libraries, but I am struggling to get started.
The attached app should show the drives on the local computer, but it does not.
I can see the drives just fine in the ViewModel, but the view is broken.

Any tips would be appreciated.
[MauiProgram.zip](https://github.com/Keflon/FunctionZero.Maui.Controls/files/12643785/MauiProgram.zip)

**Comment by mortenn** [comment]
I cleaned up the project before zipping it, but I removed too many things for it to build, but the missing asset(s) are just part of the default maui template and the missing package reference is easy enough to add :)

**Comment by Keflon** [comment]
Hi Mortenn.
I've had a quick look, and noticed the following:
- Your `ItemsSource` should be bound to a `FolderTreeViewModel`, currently it is bound to a `List<FolderTreeViewModel>`.
   - I suggest you make a 'Root' `FolderTreeViewModel` and set its `Directories` to your collection items. Something like this:


DataHunterViewModel replace `FolderTree` with `Root` ...
```csharp
public sealed class DataHunterViewModel : MvvmZeroBasePageVm
{
	public DataHunterViewModel()
	{
		var folderTree = DriveInfo.GetDrives()
				.Where(d => d.DriveType == DriveType.Fixed && d.IsReady)
				.Select(d => new FolderTreeViewModel(d)).ToList();

		Root = new FolderTreeViewModel(folderTree);

	}
        // Removed
	//public List<FolderTreeViewModel> FolderTree { get; }

        // Added
	public FolderTreeViewModel Root { get; }
}
```

FolderTreeViewModel add a constructor ...
```csharp
public FolderTreeViewModel(List<FolderTreeViewModel> folderTree)
{
	Name = "Root node";
	Directories = new ObservableCollection<FolderTreeViewModel>(folderTree);
}
```

Then in your View, bind your `ItemsSource` to `"{Binding Root}"` like this:
```csharp
<cz:TreeViewZero ItemsSource="{Binding Root}">
	<cz:TreeViewZero.TreeItemTemplate>
		<cz:TreeItemDataTemplate ChildrenPropertyName="Directories" IsExpandedPropertyName="IsExpanded" >
			<DataTemplate>
				<HorizontalStackLayout>
					<Label Text="Name=" />
					<Label Text="{Binding Name}" />
				</HorizontalStackLayout>
			</DataTemplate>
		</cz:TreeItemDataTemplate>
	</cz:TreeViewZero.TreeItemTemplate>
</cz:TreeViewZero>
```

A handy debug hint for this sort of thing can be to temporarily replace `<Label Text="{Binding Name}" />` with `<Label Text="{Binding}" />`. That way, you can see what the `BindingContext` of the `Label` is. In this case it ought to be an instance of `FolderTreeViewModel`.

One more point - TreeViewZero isn't forgiving of `null`, so if you e.g. set `ChildrenPropertyName="Directories"` you must make sure the `Directories` property is not null.  
I modified one of your contructors to do this for me ...
```csharp
public FolderTreeViewModel(DirectoryInfo dir)
{
	Name = dir.Name;
        // Do not allow Directories to be null!
	Directories = new ObservableCollection<FolderTreeViewModel>();
}
```

Let me know how you get on :)

**Comment by mortenn** [comment]
Not having multiple root nodes seems a bit weird to me, but that's a minor thing, thanks for the input

**Comment by Keflon** [comment]
You're welcome :)
