### ISSUE TITLE
Could you provide an example for TreeView in more detail?

### ISSUE THREAD

**Issue by reepmeDeveloper** [Keflon/FunctionZero.Maui.Controls#4]
Thanks for all your work...
...I really tried to use your TreeView, but even after spending 8 hours on trying to get it to work, I couldn't get it running.

Your Example-App works, but uses a reference instead of your nuget.
I get errors like these:
"Mono.Debugger.Soft.VMDisconnectedException: Exception of type 'Mono.Debugger.Soft.VMDisconnectedException' was thrown."

It would be really helpful to get a step by step introduction on how to get it working with MAUI.

**Comment by Keflon** [comment]
Thanks for letting me know. Now that I try it, I'm having a bit of trouble with the NuGet package myself.
I'll see what I can do this week.

**Comment by Keflon** [comment]
Hi @reepmeDeveloper.
What version of .NET are you using in your project?
The NuGet package is built using NET 6 and isn't working in NET 7 projects.
I've published FunctionZero.Maui.Controls version 2.0.1-pre2 built against .NET 7 and after a quick test it works in apps targeting v6 and v7 of the NET runtime.
If you find the time, can you update your NuGet package let me know if it helps?
(don't forget to check 'Include prerelease' in the NuGet file explorer or you won't see the new version)

I'll look at making a step-by-step in the near future :)

**Comment by Keflon** [comment]
Hi @reepmeDeveloper 
I'm assuming things are working for you with the latest stable NuGet package so I'm closing the ticket. If you're still having trouble please reopen.
